FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["NewstalkerWebAPI/NewstalkerWebAPI.csproj", "NewstalkerWebAPI/"]
RUN dotnet restore "NewstalkerWebAPI/NewstalkerWebAPI.csproj"
COPY . .
WORKDIR "/src/NewstalkerWebAPI"
RUN dotnet build "NewstalkerWebAPI.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "NewstalkerWebAPI.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "NewstalkerWebAPI.dll", "--swagger-enabled", "true"]
